
namespace MinesServer.GameShit.Programmator
{
    public enum ActionType
    {
        None,
        MoveUp,
        MoveLeft,
        MoveDown,
        MoveRight,
        MoveForward,
        RotateUp,
        RotateLeft,
        RotateDown,
        RotateRight,
        RotateLeftRelative,
        RotateRightRelative,
        RotateRandom,
        Dig,
        BuildBlock,
        BuildPillar,
        BuildRoad,
        BuildMilitaryBlock,
        Geology,
        Heal,
        NextRow,
        CreateFunction,
        GoTo,
        WritableStateMore,
        WritableStateLower,
        WritableState,
        RunSub,
        RunFunction,
        RunState,
        RunOnRespawn,
        RunIfTrue,
        RunIfFalse,
        Return,
        ReturnFunction,
        ReturnState,
        Start,
        Stop,
        Beep,
        CheckUp,
        CheckLeft,
        CheckDown,
        CheckRight,
        CheckUpLeft,
        CheckUpRight,
        CheckDownLeft,
        CheckDownRight,
        CheckForward,
        CheckForwardLeft,
        CheckForwardRight,
        CheckLeftRelative,
        CheckRightRelative,
        ShiftUp,
        ShiftLeft,
        ShiftDown,
        ShiftRight,
        ShiftForward,
        EnableAgression,
        DisableAgression,
        EnableAutoDig,
        DisableAutoDig,
        Flip,
        MacrosDig,
        MacrosBuild,
        MacrosHeal,
        MacrosMine,
        Or,
        And,
        IsHpLower100,
        IsHpLower50,
        IsNotEmpty,
        IsEmpty,
        IsFalling,
        IsCrystal,
        IsLivingCrystal,
        IsBoulder,
        IsSand,
        IsBreakableRock,
        IsUnbreakable,
        IsAcid,
        IsRedRock,
        IsBlackRock,
        IsGreenBlock,
        IsYellowBlock,
        IsRedBlock,
        IsPillar,
        IsQuadBlock,
        IsRoad,
        IsBox,
        CheckGun,
        FillGun,
        Last,
        BOOM,
        DISCHARGE,
        PROTON,
        VB,
        Geopack,
        ZZ,
        C190,
        Poly,
        Up,
        Craft,
        Nano,
        Rembot,
        InvDirUp,
        InvDirLeft,
        InvDirDown,
        InvDirRight,
        EnableHandMode,
        DisableHandMode,
        DebugBreak,
        DebugSet,
        Restart
    }

    public static class ActionTypeExtensions
    {
        public static ActionType GetActionType(int id)
        {
            return id switch
            {
                0 => ActionType.None,
                1 => ActionType.NextRow,
                2 => ActionType.Start,
                3 => ActionType.Stop,
                4 => ActionType.MoveUp,
                5 => ActionType.MoveLeft,
                6 => ActionType.MoveDown,
                7 => ActionType.MoveRight,
                8 => ActionType.Dig,
                9 => ActionType.RotateUp,
                10 => ActionType.RotateLeft,
                11 => ActionType.RotateDown,
                12 => ActionType.RotateRight,
                13 => ActionType.Last,
                14 => ActionType.MoveForward,
                15 => ActionType.RotateLeftRelative,
                16 => ActionType.RotateRightRelative,
                17 => ActionType.BuildBlock,
                18 => ActionType.Geology,
                19 => ActionType.BuildRoad,
                20 => ActionType.Heal,
                21 => ActionType.BuildPillar,
                22 => ActionType.RotateRandom,
                23 => ActionType.Beep,
                24 => ActionType.GoTo,
                25 => ActionType.RunSub,
                26 => ActionType.RunFunction,
                27 => ActionType.Return,
                28 => ActionType.ReturnFunction,
                29 => ActionType.CheckUpLeft,
                30 => ActionType.CheckDownRight,
                31 => ActionType.CheckUp,
                32 => ActionType.CheckUpRight,
                33 => ActionType.CheckLeft,
                35 => ActionType.CheckRight,
                36 => ActionType.CheckDownLeft,
                37 => ActionType.CheckDown,
                38 => ActionType.Or,
                39 => ActionType.And,
                40 => ActionType.CreateFunction,
                43 => ActionType.IsNotEmpty,
                44 => ActionType.IsEmpty,
                45 => ActionType.IsFalling,
                46 => ActionType.IsCrystal,
                47 => ActionType.IsLivingCrystal,
                48 => ActionType.IsBoulder,
                49 => ActionType.IsSand,
                50 => ActionType.IsBreakableRock,
                51 => ActionType.IsUnbreakable,
                52 => ActionType.IsRedRock,
                53 => ActionType.IsBlackRock,
                54 => ActionType.IsAcid,
                57 => ActionType.IsQuadBlock,
                58 => ActionType.IsRoad,
                59 => ActionType.IsRedBlock,
                60 => ActionType.IsYellowBlock,
                74 => ActionType.IsBox,
                76 => ActionType.IsPillar,
                77 => ActionType.IsGreenBlock,
                119 => ActionType.WritableStateMore,
                120 => ActionType.WritableStateLower,
                123 => ActionType.WritableState,
                131 => ActionType.ShiftUp,
                132 => ActionType.ShiftLeft,
                133 => ActionType.ShiftDown,
                134 => ActionType.ShiftRight,
                135 => ActionType.CheckForward,
                136 => ActionType.ShiftForward,
                137 => ActionType.RunState,
                138 => ActionType.ReturnState,
                139 => ActionType.RunIfFalse,
                140 => ActionType.RunIfTrue,
                141 => ActionType.MacrosDig,
                142 => ActionType.MacrosBuild,
                143 => ActionType.MacrosHeal,
                144 => ActionType.Flip,
                145 => ActionType.MacrosMine,
                146 => ActionType.CheckGun,
                147 => ActionType.FillGun,
                148 => ActionType.IsHpLower100,
                149 => ActionType.IsHpLower50,
                156 => ActionType.CheckForwardLeft,
                157 => ActionType.CheckForwardRight,
                158 => ActionType.EnableAutoDig,
                159 => ActionType.DisableAutoDig,
                160 => ActionType.EnableAgression,
                161 => ActionType.DisableAgression,
                162 => ActionType.BOOM,
                163 => ActionType.DISCHARGE,
                164 => ActionType.PROTON,
                165 => ActionType.VB,
                166 => ActionType.RunOnRespawn,
                167 => ActionType.Geopack,
                168 => ActionType.ZZ,
                169 => ActionType.C190,
                170 => ActionType.Poly,
                171 => ActionType.Up,
                172 => ActionType.Craft,
                173 => ActionType.Nano,
                174 => ActionType.Rembot,
                175 => ActionType.InvDirUp,
                176 => ActionType.InvDirLeft,
                177 => ActionType.InvDirDown,
                178 => ActionType.InvDirRight,
                179 => ActionType.EnableHandMode,
                180 => ActionType.DisableHandMode,
                181 => ActionType.DebugBreak,
                182 => ActionType.DebugSet,
                200 => ActionType.Restart,
                _ => ActionType.None
            };
        }
    }
}
